local options = require "nvchad.configs.nvimtree"
options.on_attach = function(bufnr)
  local api = require "nvim-tree.api"
  local map = vim.keymap.set
  local function opts(desc)
    return { desc = "nvim-tree: " .. desc, buffer = bufnr, noremap = true, silent = true, nowait = true }
  end
  map("n", "+", api.tree.change_root_to_node, opts "CD")
  map("n", "<2-RightMouse>", api.tree.change_root_to_node, opts "CD")
  map("n", "-", api.tree.change_root_to_parent, opts "Up")
  map("n", "gh", api.node.show_info_popup, opts "Info")
  map("n", "<Tab>", api.node.open.preview, opts "Open Preview")
  map("n", ".", api.node.run.cmd, opts "Run Command")
  map("n", "s", api.node.run.system, opts "Run System")
  map("n", "a", api.fs.create, opts "Create File Or Directory")
  map("n", "c", api.fs.copy.node, opts "Copy")
  map("n", "C", api.fs.cut, opts "Cut")
  map("n", "y", api.fs.copy.filename, opts "Copy Name")
  map("n", "Y", api.fs.copy.relative_path, opts "Copy Relative Path")
  map("n", "[c", api.node.navigate.git.prev, opts "Prev Git")
  map("n", "]c", api.node.navigate.git.next, opts "Next Git")
  map("n", "d", api.fs.remove, opts "Delete")
  map("n", "D", api.fs.trash, opts "Trash")
  map("n", "E", api.tree.expand_all, opts "Expand All")
  map("n", "]g", api.node.navigate.diagnostics.next, opts "Next Diagnostic")
  map("n", "[g", api.node.navigate.diagnostics.prev, opts "Prev Diagnostic")
  map("n", "F", api.live_filter.clear, opts "Live Filter: Clear")
  map("n", "f", api.live_filter.start, opts "Live Filter: Start")
  map("n", "g?", api.tree.toggle_help, opts "Help")
  map("n", "gy", api.fs.copy.absolute_path, opts "Copy Absolute Path")
  map("n", "gn", api.fs.copy.basename, opts "Copy Basename")
  map("n", "H", api.tree.toggle_hidden_filter, opts "Toggle Filter: Dotfiles")
  map("n", "I", api.tree.toggle_gitignore_filter, opts "Toggle Filter: Git Ignore")
  map("n", "J", api.node.navigate.sibling.last, opts "Last Sibling")
  map("n", "K", api.node.navigate.sibling.first, opts "First Sibling")
  map("n", "L", api.node.open.toggle_group_empty, opts "Toggle Group Empty")
  map("n", "M", api.tree.toggle_no_bookmark_filter, opts "Toggle Filter: No Bookmark")
  map("n", "m", api.marks.toggle, opts "Toggle Bookmark")
  map("n", "<cr>", api.node.open.edit, opts "Open")
  map("n", "<2-LeftMouse>", api.node.open.edit, opts "Open")
  map("n", "p", api.fs.paste, opts "Paste")
  map("n", "P", api.node.navigate.parent, opts "Parent Directory")
  map("n", "r", api.fs.rename_basename, opts "Rename: Basename")
  map("n", "R", api.fs.rename_sub, opts "Rename: Omit Filename")
  map("n", "u", api.fs.rename_full, opts "Rename: Full Path")
  map("n", "<C-r>", api.tree.reload, opts "Refresh")
end
return options
