local map = vim.keymap.set
local dap = require "dap"
local ui = require "dapui"

map("n", "<F5>", function()
  dap.continue()
end, { desc = "start" })
map("n", "<leader>dc", function()
  dap.continue()
end, { desc = "start/continue (F5)" })
map("n", "<F29>", function()
  dap.restart_frame()
end, { desc = "restart" })
map("n", "<leader>dr", function()
  dap.restart_frame()
end, { desc = "restart (Ctrl+F5)" })
map("n", "<F17>", function()
  dap.terminate()
end, { desc = "stop" })
map("n", "<leader>dQ", function()
  dap.terminate()
end, { desc = "stop (Shift+F5)" })
map("n", "<F6>", function()
  dap.pause()
end, { desc = "pause" })
map("n", "<leader>dp", function()
  dap.pause()
end, { desc = "pause (F6)" })
map("n", "<leader>dq", function()
  dap.close()
end, { desc = "close session" })

map("n", "<F9>", function()
  dap.toggle_breakpoint()
end, { desc = { "toggle breakpoint" } })
map("n", "<leader>db", function()
  dap.toggle_breakpoint()
end, { desc = "toggle breakpoint (F9)" })
map("n", "<F21>", function()
  vim.ui.input({ prompt = "Condition: " }, function(condition)
    if condition then
      require("dap").set_breakpoint(condition)
    end
  end)
end, { desc = "conditional breakpoint" })
map("n", "<leader>dB", function()
  vim.ui.input({ prompt = "Condition: " }, function(condition)
    if condition then
      require("dap").set_breakpoint(condition)
    end
  end)
end, { desc = "conditional breakpoint (Shift+F9)" })
map("n", "<leader>dx", function()
  dap.clear_breakpoints()
end, { desc = "clear breakpoints" })

map("n", "<F10>", function()
  dap.step_over()
end, { desc = "step over" })
map("n", "<leader>do", function()
  dap.step_over()
end, { desc = "step over (F10)" })
map("n", "<F11>", function()
  dap.step_into()
end, { desc = "step into" })
map("n", "<leader>di", function()
  dap.step_into()
end, { desc = "step into (F11)" })
map("n", "<F23>", function()
  dap.step_out()
end, { desc = "step out" })
map("n", "<leader>dO", function()
  dap.step_out()
end, { desc = "step out (Shift+F11)" })
map("n", "<leader>ds", function()
  dap.run_to_cursor()
end, { desc = "run to cursor" })

map("n", "<leader>du", function()
  ui.toggle()
end, { desc = "toggle UI" })
map("n", "<leader>dh", function()
  ui.eval()
end, { desc = "hover evaluation" })
map("v", "<leader>dh", function()
  ui.eval()
end, { desc = "hover evaluation" })
map("n", "<leader>dH", function()
  vim.ui.input({ prompt = "Expression: " }, function(expr)
    if expr then
      require("dapui").eval(expr, { enter = true })
    end
  end)
end, { desc = "hover evaluation of expression" })
