local map = vim.keymap.set
map("n", "<F5>", function()
  require("dap").continue()
end)
map("n", "<F9>", function()
  require("dap").toggle_breakpoint()
end, { desc = { "toggle breakpoint" } })
map("n", "<F10>", function()
  require("dap").step_over()
end)
map("n", "<F11>", function()
  require("dap").step_into()
end)
map("n", "<F12>", function()
  require("dap").step_out()
end)
map("n", "<leader>db", function()
  require("dap").toggle_breakpoint()
end, { desc = { "toggle breakpoint" } })
map("n", "<leader>du", function()
  require("dapui").toggle()
end, { desc = "Toggle UI" })
